#!/usr/bin/env python3
"""
Model assignment from quality: which tasks earn a cheaper model, which need a better one.
  assign.py [--days 14]   -> writes state/system/assignments.md and prints it
Never edits task files. Items are attributed to the task whose task_start..task_end interval (same fire) contains them.
Signals: rate up/down, tags (go/explore/add_target/approve) vs skip/prune, check scores. Cost from task_end.
"""
import argparse, datetime as dt, json, os, re
from pathlib import Path

HOME = Path(os.environ.get("ORBIT_HOME", Path(__file__).resolve().parents[1]))
EVENTS = HOME / "briefs" / "data" / "events.jsonl"
OUT = HOME / "state" / "system" / "assignments.md"
TIER = ["haiku", "sonnet", "fable"]


def ts(e): return dt.datetime.strptime(e["ts"][:19], "%Y-%m-%dT%H:%M:%S")
def tier(model): return next((i for i, k in enumerate(TIER) if k in (model or "").lower()), 1)


def analyze(days):
    ev = [json.loads(l) for l in EVENTS.read_text(encoding="utf-8").splitlines() if l.strip()] if EVENTS.exists() else []
    since = dt.datetime.now() - dt.timedelta(days=days)
    ev = [e for e in ev if ts(e) > since]
    intervals = []  # (fire, task, model, lane, start, end, cost)
    starts = {}
    for e in ev:
        if e.get("type") == "task_start": starts[(e["fire"], e["task"])] = e
        elif e.get("type") == "task_end" and (e["fire"], e["task"]) in starts:
            s = starts.pop((e["fire"], e["task"]))
            intervals.append((e["fire"], e["task"], e.get("model", ""), e.get("lane", ""), ts(s), ts(e), float(e.get("cost_usd") or 0)))
    item_task = {}
    for e in ev:
        if e.get("type") == "item":
            for f, t, m, l, a, b, c in intervals:
                if e.get("fire") == f and a <= ts(e) <= b and e["id"] not in item_task: item_task[e["id"]] = t
    score = {}
    for e in ev:
        if e.get("type") != "item_action" or e.get("id") not in item_task: continue
        t = item_task[e["id"]]; s = score.setdefault(t, {"up": 0, "down": 0, "tag": 0, "drop": 0, "checks": []})
        a = e.get("action")
        if a == "rate": s["up" if e.get("value") == "up" else "down"] += 1
        elif a in ("go", "explore", "add_target", "approve"): s["tag"] += 1
        elif a in ("skip", "prune"): s["drop"] += 1
        elif a == "check":
            m = re.match(r"(\d+) of (\d+)", str(e.get("result", "")))
            if m: s["checks"].append(int(m.group(1)) / int(m.group(2)))
    rows = []
    for t in sorted({i[1] for i in intervals}):
        runs = [i for i in intervals if i[1] == t]; model = runs[-1][2]; cost = sum(i[6] for i in runs) / len(runs)
        s = score.get(t, {"up": 0, "down": 0, "tag": 0, "drop": 0, "checks": []})
        good = s["up"] + s["tag"] + sum(1 for c in s["checks"] if c >= 0.8); bad = s["down"] + s["drop"] + sum(1 for c in s["checks"] if c < 0.6)
        n = good + bad; q = good / n if n else None
        cur = tier(model); proposal = "keep"; why = "not enough signal (%d actions)" % n
        if n >= 6 and q is not None:
            if q >= 0.8 and cur > 0: proposal = "try %s" % TIER[cur - 1]; why = "%.0f%% positive over %d actions; a cheaper model may hold" % (q * 100, n)
            elif q <= 0.4 and cur < 2: proposal = "raise to %s" % TIER[cur + 1]; why = "%.0f%% positive over %d actions" % (q * 100, n)
            else: why = "%.0f%% positive over %d actions" % (q * 100, n)
        rows.append((t, model, len(runs), cost, n, q, proposal, why))
    lines = ["# Model assignments (last %d days)" % days, "", "Generated by system/assign.py. Proposals only; apply by editing the task's `model:` or approving a retro proposal.", "",
             "| task | model | runs | avg cost | signals | positive | proposal | evidence |", "|---|---|---|---|---|---|---|---|"]
    for t, m, r, c, n, q, p, w in rows:
        lines.append("| %s | %s | %d | $%.2f | %d | %s | %s | %s |" % (t, m, r, c, n, ("%.0f%%" % (q * 100)) if q is not None else "n/a", p, w))
    OUT.parent.mkdir(parents=True, exist_ok=True); OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--days", type=int, default=14)
    print(analyze(ap.parse_args().days))


if __name__ == "__main__":
    main()
